name: CI - Test & Validate

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Run integration tests
        run: npm run test:integration
        continue-on-error: true
      
      - name: Run security audit
        run: npm run test:security
        continue-on-error: true
  
  validate:
    name: Validate Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate manifest.json
        run: |
          node -e "const manifest = require('./manifest.json'); \
          if (manifest.manifest_version !== 3) throw new Error('Must be Manifest V3'); \
          if (!manifest.name || !manifest.version) throw new Error('Missing required fields'); \
          console.log('✅ Manifest valid');"
      
      - name: Validate file structure
        run: |
          test -f manifest.json || exit 1
          test -f src/service-worker.js || exit 1
          test -f src/content.js || exit 1
          test -f src/popup.html || exit 1
          echo "✅ File structure valid"
      
      - name: Check for sensitive data
        run: |
          if grep -r "api_key\|secret\|password" src/ --include="*.js" | grep -v "example\|test\|mock"; then
            echo "⚠️ Potential sensitive data found"
            exit 1
          fi
          echo "✅ No sensitive data detected"
  
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Clerk bundle
        run: npm run build:clerk
      
      - name: Validate build output
        run: |
          test -f src/vendor/clerk.js || exit 1
          echo "✅ Build successful"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-build
          path: |
            manifest.json
            src/
            assets/
          retention-days: 7

